[package]
name = "ferrisflash"
version = "0.2.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.0", features = ["derive"] }
flate2 = "1.1"
zstd = "0.13"